

INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','0','0','Entrée refusée. Niveau d\'accès insuffisant.','14','0','0','0','0','15426','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','1','0','Accès à l\'Archivum autorisé. Méchanisme de protection anti-intrusion suspendu.','14','0','0','0','0','15427','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','2','0','Une demande d\'initiation. La mesure de sécurité Algalon est un signal d\'urgence automatique qui suit une transmission de Prime Designate.','14','0','0','0','0','15428','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','3','0','Affirmatif. La marque temps de la destruction du Prime Designate Loken coïncide vec l\'activation du signal.','14','0','0','0','0','15429','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','4','0','Je cherche .. La destruction du Prime Designate est considérée comme le premier signe avertisseur d\'effondrement planétaire systémique. L\'arrivée de l\'entité d\'observateur d\'Algalon est suivie de diagnostics planétaires qui émettent un des deux signaux de réponse possibles. Le code de réponse Alpha, qui signale que \"tout va bien\" et le code de réponse Omega qui signale une re-création planétaire.','14','0','0','0','0','15430','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','5','0','décomposition de la planète et de ses organismes vivants en leurs éléments de base : métaux, rocs, gaz. Puis vient une période de reconstitution de chaque élément en sa forme planétaire d\'oriigine.','14','0','0','0','0','15431','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','6','0','Demande rejetée. Les codes de réponse sont construits dans l\'entité de l\'observateur d\'Algalon. Il est à la fois le messager et le message.','14','0','0','0','0','15432','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','7','0','Le diagnostic d\'Algalon décèle un risque de corruption systémique du Dieu Ancien, dans les fonctions planétaires vitales. Calcul de la probabilité d\'un code de réponse Omega en cours.','14','0','0','0','0','15433','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','8','0','quatre vingt dix neuf virgule quatre vingt dix neuf pour cent.','14','0','0','0','0','15434','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','9','0','La decimale est recursive biensur.','14','0','0','0','0','15435','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','10','0','Accès refusé. Le dévérouillage requiert une vérification manuelle des sceaux des quatres gardiens.','14','0','0','0','0','15436','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','11','0','Les quatres gardiens d\'Ulduar : Freya, Thorim, Hodir et Mimiron. Les sceaux sont liés à leur intégrité physique et mentale. Les quatres sceaux sont nécessaires pour accéder au Planétarium.','14','0','0','0','0','15437','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','12','0','Analyse de l\'état des gardiens en cours. Veuillez patienter.','14','0','0','0','0','15438','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','13','0','Corruption détectée. Une influence extérieure cherche a obtenir le contrôle des gardiens. Les sceaux ne sont plus une sécurité fiable.','14','0','0','0','0','15439','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','14','0','Un utilisation suffisante de force générerait une réinitialisation des fonctions des veilleurs, ce qui supprimerait l\'influence extérieure.','14','0','0','0','0','15440','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','15','0','Quant à ne pas mettre les sceaux en danger en le faisant, je peux analyser l\'état de chacun des veilleurs et vous donner l\'information à la completion des calculs.','14','0','0','0','0','15441','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','16','0',' Commencing Watcher Freya status analysis.','16','0','0','0','0','15442','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','17','0','Watcher\'s powers augmented by presence of Elder servants.','17','0','0','0','0','15443','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','18','0','Analyzing Elder Brightleaf enhancement. Persistent area defenses powered by solar amplification.','18','0','0','0','0','15444','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','19','0','Elder Stonebark analysis reveals a sonic defense that disrupts use of magic.','19','0','0','0','0','15445','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','20','0',' Elder Ironbranch scans have uncovered plant based immobilization mechanisms.','20','0','0','0','0','15446','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','21','0',' In addition, my analysis links each Elder to an increase in Freya spell-casting, physical or summoning capabilities.','21','0','0','0','0','15447','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','22','0','Destruction of Elder servants will result in lost of enhancements of Watcher Freya. However permanent damage to Freya\'s person and possessions including her Watcher sigil highly probable.','22','0','0','0','0','15448','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','23','0','Commencing Watcher Hodir status analysis.','23','0','0','0','0','15453','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','24','0','Hodir\'s sigil appears to be located inside a cache of artifacts.','24','0','0','0','0','15454','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','25','0','Watcher Hodir\'s temperament and behavior highly unstable. Destruction of cache highly probable during prolonged combat.','25','0','0','0','0','15455','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','26','0','Allies imprisoned in the field of battle are likely to provide synergies and minimize combat duration.','26','0','0','0','0','15456','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','27','0','Preservation of cache is essential to recovering Hodir\'s sigil.','27','0','0','0','0','15457','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','28','0','Commencing Watcher Mimiron status analysis.','28','0','0','0','0','15458','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','29','0','Watcher Mimiron\'s sigil is linked to a self-destruct mechanism connected to entirety of the Corridors of Ingenuity.','29','0','0','0','0','15459','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','30','0','Trigger for self-destruct mechanism is code named \"Big Red Button\". Mimiron\'s own creation.','30','0','0','0','0','15460','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','31','0','To retrieve Mimiron\'s sigil, initiate self-destruct sequence and defeat Mimiron before its completion.','31','0','0','0','0','15461','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','32','0','Self-destruct sequence finalized. Have a nice day.','32','0','0','0','0','15462','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','33','0','Commencing Watcher Thorim status analysis.','33','0','0','0','0','15449','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','34','0','An external influence under illusory guise of Thorim\'s deceased mate Sif has been detected.','34','0','0','0','0','15450','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','35','0','Mental interference from this presence dangerously close from triggering partial memory damage.','35','0','0','0','0','15451','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('500000','36','0','Tactical analysis suggest approaching the arena from the front and splitting secondary force through a side passage at the ground level. This will maximize odds of reaching Thorim\'s outlook before mental domination by external presence is complete.','36','0','0','0','0','15452','');



INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','0','0','Eh bien, c\'est ce que l\'on appelle une bonne découverte !','14','0','0','0','0','15808','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','1','0','Je vais t\'en donner de la sécurité, moi! misérable machine. La voilà de nouveau . la clé de Norgannon.','14','0','0','0','0','15809','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','2','0','Ca resssemble juste à toutes les autres archives des titans, que mes gars ont trouvées, seulement plus anciennes et plus vollumineuses.','14','0','0','0','0','15810','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','3','0','Attends une seconde : ça a l\'air bizarre! A côté de ce clignotant... Qu\'est-ce que ce signal d\'Algalon ?','14','0','0','0','0','15811','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','4','0','Prima Designe ? Où ai-je déjà entendu ça ? Par la barbe de mon grand-père, Loken est le Prima Designe d\'Azeroth. C\'est la mort de Loken qui a tout déclenché!','14','0','0','0','0','15812','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','5','0',' Et alors ? Qui écoute du signal ? qu\'est-ce qui va se passer ?','14','0','0','0','0','15813','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','6','0','Re-création planétaire ? Parle clairement, satanée machine !','14','0','0','0','0','15814','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','7','0','Z\'entendez les gars ? C\'est seulement la fin du monde. Alors qu\'est-ce que tu attends, machine rouillée ? Initie le code de réponse Alpha. Tout va bien ! C\'est moi qui régale ! ','14','0','0','0','0','15815','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','8','0','Alors, qu\'est-ce que cet Algalon va rechercher avec ses diagnostics ? Quelles sont nos chances ?','14','0','0','0','0','15816','');
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probabilitINSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emotINSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES('33235','14','0','Je rêve depuis des années de vagabonder dans la demeure des titans... Je n\'aurais jamais cru m\'opposer un jour à leurs créations... ','14','0','0','0','0','15822','');
